name: Test deployment

on:
  workflow_dispatch

jobs:
  build_publish_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: testing

    steps:
    
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for updated images
        id: updated-images
        run: |
          UPDATED=$(git diff --name-only HEAD^ HEAD)
          UPDATED_IMAGES=$(echo "$UPDATED" | grep "images" | sed "s/\/lambda_function.py//g" | sort | uniq)
          
          echo "UPDATED: "
          echo "$UPDATED"

          echo "UPDATED_IMAGES:"
          echo "$UPDATED_IMAGES"
