name: Test deployment

on:
  workflow_dispatch

env:
  AWS_REGION: "us-east-1"

jobs:
  build_publish_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: testing

    steps:
    
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for updated images
        id: updated-images
        run: |
          UPDATED=$(git diff --name-only HEAD^ HEAD)
          UPDATED_PIPELINE_IMAGES==$(echo "$UPDATED" | grep -o '+_pipeline/[^/]\+/' | uniq)
          UPDATED_SOLVER_IMAGES=$(echo "$UPDATED" | grep -o '+_olver/' | uniq)
          UPDATED_IMAGES="$UPDATED_PIPELINE_IMAGES $UPDATED_SOLVER_IMAGES"
          
          if [ -n "$UPDATED_IMAGES" ]; then
            echo "These images have been updated:"
            echo "$UPDATED_IMAGES"
          else
            echo "No Docker images have been updated. Skipping deployment."
            exit 0
          fi